# docker-compose.yml — {{AGENT_DISPLAY_NAME}}
# Generated by setup.sh. Edit modules/docker-compose.yml.tpl to change.

services:
  {{AGENT_NAME}}:
    image: {{DOCKER_IMAGE_TAG}}
    container_name: {{AGENT_NAME}}
    build:
      context: ./docker
      args:
        UID: "{{DOCKER_UID}}"
        GID: "{{DOCKER_GID}}"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:size=100m
    restart: unless-stopped
    stop_grace_period: 30s
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace
      # State (login, pairing, sessions, plugin cache) lives inside the
      # workspace so the directory IS the agent — portable via rsync/cp,
      # immune to `docker compose down -v`, removed only with the
      # workspace itself.
      - ./.state:/home/agent
    env_file:
      - ./.env
