# docker-compose.yml — {{AGENT_DISPLAY_NAME}}
# Generated by setup.sh. Edit modules/docker-compose.yml.tpl to change.

services:
  {{AGENT_NAME}}:
    image: {{DOCKER_IMAGE_TAG}}
    container_name: {{AGENT_NAME}}
    build:
      context: ./docker
      args:
        UID: "{{DOCKER_UID}}"
        GID: "{{DOCKER_GID}}"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:size=100m
    restart: unless-stopped
    stop_grace_period: 30s
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace
      - {{DOCKER_STATE_VOLUME}}:/home/agent
    env_file:
      - ./.env

volumes:
  {{DOCKER_STATE_VOLUME}}:
    name: {{DOCKER_STATE_VOLUME}}
