# .env — secrets for {{AGENT_DISPLAY_NAME}}
# Generated by setup.sh. NEVER commit this file.

# Claude headless auth — paste the token from `claude setup-token` (run on the
# host). Set this to boot fully operational without interactive /login.
CLAUDE_CODE_OAUTH_TOKEN=

{{#if NOTIFICATIONS_CHANNEL_IS_TELEGRAM}}
# Telegram notifications
NOTIFY_BOT_TOKEN=
NOTIFY_CHAT_ID=
{{/if}}

{{#each MCPS_ATLASSIAN}}
# Atlassian workspace: {{name}}
ATLASSIAN_{{NAME}}_CONFLUENCE_URL={{url}}/wiki
ATLASSIAN_{{NAME}}_CONFLUENCE_USERNAME={{email}}
ATLASSIAN_{{NAME}}_JIRA_URL={{url}}
ATLASSIAN_{{NAME}}_JIRA_USERNAME={{email}}
ATLASSIAN_{{NAME}}_TOKEN=
{{/each}}

{{#if MCPS_GITHUB_ENABLED}}
# GitHub MCP
GITHUB_PAT=
{{/if}}
