# .env — secrets for {{AGENT_DISPLAY_NAME}}
# Generated by setup.sh. NEVER commit this file.

# Claude headless auth — paste the token from `claude setup-token` (run on the
# host). Set this to boot fully operational without interactive /login.
CLAUDE_CODE_OAUTH_TOKEN=

{{#if NOTIFICATIONS_CHANNEL_IS_TELEGRAM}}
# Telegram notifications
NOTIFY_BOT_TOKEN=
NOTIFY_CHAT_ID=
{{/if}}

{{#each MCPS_ATLASSIAN}}
# Atlassian workspace: {{name}}
ATLASSIAN_{{NAME}}_CONFLUENCE_URL={{url}}/wiki
ATLASSIAN_{{NAME}}_CONFLUENCE_USERNAME={{email}}
ATLASSIAN_{{NAME}}_JIRA_URL={{url}}
ATLASSIAN_{{NAME}}_JIRA_USERNAME={{email}}
ATLASSIAN_{{NAME}}_TOKEN=
{{/each}}

{{#if MCPS_GITHUB_ENABLED}}
# GitHub MCP
GITHUB_PAT=
{{/if}}

# Round-trip voice over Telegram (032, opt-in via features.voice.enabled).
# Required to activate; a missing key degrades to today's text-only behaviour
# with a one-time boot WARN. Optional tuning knobs override the built-in
# defaults (transcription cap: 300s; spoken-reply cut budget: 900 chars ≈ 60 s).
# The closing phrase and the currency word are agent.yml fields
# (features.voice.{signoff,currency}) — compose environment: wins over this
# file, so they are NOT knobs here.
ELEVENLABS_API_KEY=
# TELEGRAM_VOICE_MAX_NOTE_SECONDS=300
# TELEGRAM_VOICE_SPOKEN_CHAR_CAP=900
