#!/usr/bin/env bats
# 021-local-secret-delivery: scripts/lib/env_file.sh — the allowlisted reader
# (env_file_get) and the portable-subset linter (env_file_lint). Contract:
# specs/021-local-secret-delivery/contracts/env-file-format.md. Host-runnable,
# no systemd needed — this is the proxy for parsing behavior we cannot test
# on a macOS host.

load helper

setup() {
  setup_tmp_dir
  load_lib env_file
}

teardown() { teardown_tmp_dir; }

# ─── env_file_get ────────────────────────────────────────────────────────

@test "env_file_get: returns the value of a simple KEY=value line" {
  printf 'FOO=bar\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$status" -eq 0 ]
  [ "$output" = "bar" ]
}

@test "env_file_get: KEY= with empty value returns empty string" {
  printf 'FOO=\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$status" -eq 0 ]
  [ "$output" = "" ]
}

@test "env_file_get: missing key returns empty string, exit 0" {
  printf 'OTHER=x\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$status" -eq 0 ]
  [ "$output" = "" ]
}

@test "env_file_get: missing file returns empty string, exit 0" {
  run env_file_get FOO "$TMP_TEST_DIR/does-not-exist.env"
  [ "$status" -eq 0 ]
  [ "$output" = "" ]
}

@test "env_file_get: last match wins on a duplicate key" {
  printf 'FOO=first\nFOO=second\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$output" = "second" ]
}

@test "env_file_get: strips one layer of matching double quotes" {
  printf 'FOO="bar"\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$output" = "bar" ]
}

@test "env_file_get: strips one layer of matching single quotes" {
  printf "FOO='bar'\n" > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$output" = "bar" ]
}

@test "env_file_get: mismatched quotes are NOT stripped" {
  printf 'FOO="bar'"'"'\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [[ "$output" == *'"'* ]]
}

@test "env_file_get: a value containing = splits on the FIRST = only" {
  printf 'TOKEN=abc=def=ghi\n' > "$TMP_TEST_DIR/.env"
  run env_file_get TOKEN "$TMP_TEST_DIR/.env"
  [ "$output" = "abc=def=ghi" ]
}

@test "env_file_get: a value containing a colon (telegram-token shape) is intact" {
  printf 'TOK=123456789:AAAbbbCCCdddEEEfffGGGhhh\n' > "$TMP_TEST_DIR/.env"
  run env_file_get TOK "$TMP_TEST_DIR/.env"
  [ "$output" = "123456789:AAAbbbCCCdddEEEfffGGGhhh" ]
}

@test "env_file_get: ignores comment and blank lines" {
  printf '# a comment\n\nFOO=bar\n' > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ "$output" = "bar" ]
}

@test "env_file_get SECURITY: never executes file content (canary must not fire)" {
  # The canary line looks like a command substitution assignment. If the
  # reader ever sources/evals the file, this file gets created. It must NOT.
  local canary="$TMP_TEST_DIR/pwned"
  cat > "$TMP_TEST_DIR/.env" << EOF
EVIL=\$(touch "$canary")
NOTIFY_BOT_TOKEN=real-token
EOF
  run env_file_get NOTIFY_BOT_TOKEN "$TMP_TEST_DIR/.env"
  [ "$output" = '$(touch "'"$canary"'")' ] || [ "$output" != "real-token-if-executed" ]
  run env_file_get NOTIFY_BOT_TOKEN "$TMP_TEST_DIR/.env"
  [ "$output" = "real-token" ]
  # The load-bearing assertion, kept LAST per the suite's bats hazard:
  [ ! -e "$canary" ]
}

@test "env_file_get SECURITY: does not eval a value containing a backtick command" {
  local canary="$TMP_TEST_DIR/pwned-backtick"
  printf 'FOO=`touch %s`\n' "$canary" > "$TMP_TEST_DIR/.env"
  run env_file_get FOO "$TMP_TEST_DIR/.env"
  [ ! -e "$canary" ]
}

# ─── env_file_lint ───────────────────────────────────────────────────────

@test "env_file_lint: a wizard-shaped clean file produces zero findings, exit 0" {
  cat > "$TMP_TEST_DIR/.env" << 'EOF'
# Generated by setup.sh
# NEVER commit this file.

CLAUDE_CODE_OAUTH_TOKEN=

NOTIFY_BOT_TOKEN=123456789:AAAbbbCCCdddEEEfffGGGhhh
NOTIFY_CHAT_ID=987654321

ATLASSIAN_WORK_CONFLUENCE_URL=https://work.atlassian.net/wiki
ATLASSIAN_WORK_CONFLUENCE_USERNAME=a@b.com
ATLASSIAN_WORK_JIRA_URL=https://work.atlassian.net
ATLASSIAN_WORK_JIRA_USERNAME=a@b.com
ATLASSIAN_WORK_TOKEN=abc123
GITHUB_PAT=ghp_abcdefghijklmnop
EOF
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "env_file_lint: trailing backslash is flagged (systemd swallows the next line)" {
  printf 'FOO=abc\\\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
  [[ "$output" == *"line 1"* ]]
  [[ "$output" == *"FOO"* ]]
}

@test "env_file_lint: export-prefixed assignment is flagged (invalid systemd name)" {
  printf 'export FOO=bar\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
  [[ "$output" == *"line 1"* ]]
}

@test "env_file_lint: 'KEY: v' (YAML-style) is flagged" {
  printf 'FOO: bar\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
}

@test "env_file_lint: a bare KEY with no = is flagged" {
  printf 'JUSTAKEY\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
}

@test "env_file_lint: a semicolon-prefixed line is flagged (fails compose, not systemd)" {
  printf ';FOO=bar\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
}

@test "env_file_lint: an inline ' # ' comment on a value is flagged" {
  printf 'FOO=bar # a note\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
  [[ "$output" == *"FOO"* ]]
}

@test "env_file_lint: a \$ inside a value is flagged (compose interpolates, systemd doesn't)" {
  printf 'FOO=a\$B\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
}

@test "env_file_lint: a leading quote on a value is flagged" {
  printf 'FOO="bar"\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
}

@test "env_file_lint: a carriage return in the file is flagged" {
  printf 'FOO=bar\r\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
}

@test "env_file_lint: findings NEVER contain the offending value" {
  printf 'GITHUB_PAT=ghp_supersecrettoken12345\\\n' > "$TMP_TEST_DIR/.env"
  run env_file_lint "$TMP_TEST_DIR/.env"
  [ "$status" -eq 1 ]
  # Load-bearing negative — last, per the suite's bats hazard.
  if printf '%s' "$output" | grep -q 'ghp_supersecrettoken12345'; then false; fi
}

@test "env_file_lint: missing file is clean (nothing to lint), exit 0" {
  run env_file_lint "$TMP_TEST_DIR/nope.env"
  [ "$status" -eq 0 ]
}
