#!/bin/bash
# In-container first-run wizard. Collects secrets the host wizard deferred
# (Telegram bot token, GitHub PAT, per-Atlassian-workspace tokens) and
# merges them into /workspace/.env without destroying whatever the host
# wizard already wrote. Exits so `unless-stopped` restarts the container
# into steady state.
set -euo pipefail

ENV_FILE="/workspace/.env"
AGENT_YML="/workspace/agent.yml"

echo ""
echo "╭──────────────────────────────────────────────╮"
echo "│ First-run setup for your dockerized agent    │"
echo "│ (values are merged into /workspace/.env 0600)│"
echo "╰──────────────────────────────────────────────╯"
echo ""

# Ensure the env file exists with a header and 0600 perms. If the host
# wizard already wrote some lines (Atlassian URLs, NOTIFY_* placeholders,
# etc.), we preserve them — we only replace/add our own keys below.
umask 077
if [ ! -f "$ENV_FILE" ]; then
  {
    echo "# Generated by docker/scripts/wizard-container.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# NEVER commit this file."
    echo
  } > "$ENV_FILE"
fi
chmod 0600 "$ENV_FILE"

# Upsert KEY=VALUE into $ENV_FILE. Replaces an existing line in place
# (preserving surrounding content) or appends a new one. Uses `|` as the
# sed delimiter — bot tokens / PATs / basic-auth tokens never contain `|`.
update_env_var() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    echo "${key}=${value}" >> "$ENV_FILE"
  fi
}

# ── Enrich CLAUDE.md with live workspace info ──
# Runs before the Telegram prompt so the agent's base memory file has an
# up-to-date snapshot of commands/architecture before the first chat. Uses
# `claude --print` (one-shot, non-interactive). Claude is already
# authenticated at this point (wizard only fires after /login).
# Failure is non-fatal — the template-rendered CLAUDE.md still works.
CLAUDE_MD="/workspace/CLAUDE.md"
if [ -f "$CLAUDE_MD" ] && command -v claude >/dev/null 2>&1; then
  echo "▸ Refreshing agent memory (CLAUDE.md) — reading workspace..."
  # The prompt lives in a temp file so we avoid escaping headaches in the
  # bash-3 syntax checker when the content contains apostrophes.
  update_prompt_file=$(mktemp)
  cat > "$update_prompt_file" <<'PROMPT'
Update /workspace/CLAUDE.md to reflect the current workspace.

Preserve VERBATIM (do not edit or reorder) the Identity, User, Core
Truths, Boundaries, and Execution Strategy sections. They come from
agent.yml and carry the agent personality.

Add or refresh, only if missing or stale, sections for:
- Common commands the engineer actually runs (inspect setup.sh,
  docker/scripts/heartbeatctl, scripts/heartbeat/, and tests/ for
  real invocations — do not invent).
- Architecture that requires reading multiple files to understand
  (entrypoint → crond → start_services → tmux; the render engine; the
  heartbeat observability pipeline runs.jsonl + state.json).
- Test conventions (bats + fixtures, how to run one test file or one
  test by name).

Edit in place with the Edit tool, never Write. Do not touch files
other than CLAUDE.md. If everything is already well-documented, make
no edits and say so.
PROMPT
  # Timeout so a stuck claude does not block the first-run wizard forever.
  # Track success so we don't print the green "✓ refreshed" right after a
  # warning that it was skipped (confusing UX prior to this fix).
  update_prompt=$(cat "$update_prompt_file")
  refresh_ok=true
  if command -v gum >/dev/null 2>&1; then
    gum spin --title "Running claude --print to update CLAUDE.md..." -- \
      timeout 90 claude --print "$update_prompt" >/tmp/claude-md-update.log 2>&1 \
      || refresh_ok=false
  else
    timeout 90 claude --print "$update_prompt" >/tmp/claude-md-update.log 2>&1 \
      || refresh_ok=false
  fi
  rm -f "$update_prompt_file"
  if [ "$refresh_ok" = true ]; then
    echo "  ✓ CLAUDE.md refreshed"
  else
    echo "  ⚠ CLAUDE.md update skipped (timeout or claude error — see /tmp/claude-md-update.log)"
  fi
  echo ""
fi

# ── Telegram bot token (required for the channel plugin) ──
BOT=$(gum input --password --prompt "Telegram bot token (from @BotFather): ")
if [ -z "$BOT" ]; then
  echo "ERROR: Telegram bot token cannot be empty." >&2
  exit 1
fi
update_env_var TELEGRAM_BOT_TOKEN "$BOT"

# ── GitHub PAT (optional — for gh CLI and the github MCP) ──
# If the host wizard already captured a GITHUB_PAT, don't ask again.
existing_gh_pat=$(grep "^GITHUB_PAT=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2-)
if [ -z "$existing_gh_pat" ]; then
  if gum confirm "Add a GitHub Personal Access Token (for gh / MCP)?" --default=no; then
    GH_PAT=$(gum input --password --prompt "GitHub PAT: ")
    if [ -n "$GH_PAT" ]; then
      update_env_var GITHUB_PAT "$GH_PAT"
    fi
  fi
else
  echo "  ✓ GITHUB_PAT already set by host wizard — skipping."
fi

# ── Atlassian workspace tokens ──
# The host wizard captures each workspace's alias/URL/email into agent.yml
# but defers the token to this step. We iterate the array and prompt for
# any token that isn't already set in .env.
if [ -f "$AGENT_YML" ] && command -v yq >/dev/null 2>&1; then
  atl_count=$(yq '.mcps.atlassian | length' "$AGENT_YML" 2>/dev/null || echo 0)
  if [ "${atl_count:-0}" -gt 0 ]; then
    echo ""
    echo "Atlassian workspaces configured in agent.yml:"
    for i in $(seq 0 $((atl_count - 1))); do
      ws_name=$(yq ".mcps.atlassian[$i].name"  "$AGENT_YML")
      ws_url=$( yq ".mcps.atlassian[$i].url"   "$AGENT_YML")
      upper=$(echo "$ws_name" | tr '[:lower:]' '[:upper:]')
      var="ATLASSIAN_${upper}_TOKEN"
      # Skip if already populated
      existing=$(grep "^${var}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2-)
      if [ -n "$existing" ]; then
        echo "  ✓ ${var} already set — skipping"
        continue
      fi
      tok=$(gum input --password --prompt "${var} (${ws_url}): ")
      if [ -n "$tok" ]; then
        update_env_var "$var" "$tok"
      else
        echo "  ⚠ ${var} left blank — the atlassian-${ws_name} MCP will fail until you fill it in"
        update_env_var "$var" ""
      fi
    done
  fi
fi

echo ""
echo "✓ /workspace/.env ready. Exiting — Docker will restart into steady state."
exit 0
