#!/bin/sh
# Refresh /workspace/CONTAINER.md with live runtime details. Invoked by
# entrypoint.sh on every container boot (and cheap enough that we could also
# call it on demand later). The agent reads it via CLAUDE.md's pointer so it
# knows, with accurate data, that it runs inside a Docker container.
set -eu

WORKSPACE=${WORKSPACE:-/workspace}
OUT="$WORKSPACE/CONTAINER.md"

# uname bits
KERNEL=$(uname -sr 2>/dev/null || echo "unknown")
ARCH=$(uname -m 2>/dev/null || echo "unknown")

# OS pretty name
OS_NAME="unknown"
if [ -r /etc/os-release ]; then
  . /etc/os-release 2>/dev/null || true
  OS_NAME="${PRETTY_NAME:-${NAME:-unknown}}"
fi

# Hostname shown to container processes (the Docker-assigned short id by
# default) — useful for the agent to tell apart container vs host names.
CONTAINER_HOSTNAME=$(hostname 2>/dev/null || echo "unknown")

# Host machine name as declared in agent.yml (survives bind-mount).
HOST_NAME="unknown"
if command -v yq >/dev/null 2>&1 && [ -r "$WORKSPACE/agent.yml" ]; then
  HOST_NAME=$(yq '.deployment.host' "$WORKSPACE/agent.yml" 2>/dev/null || echo "unknown")
fi

# Agent user mapping (for bind-mount ownership hints).
AGENT_UID=$(id -u agent 2>/dev/null || echo "?")
AGENT_GID=$(id -g agent 2>/dev/null || echo "?")

# First non-loopback IPv4 on the container's bridge.
CONTAINER_IP=$(ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | head -1 || echo "")
[ -z "$CONTAINER_IP" ] && CONTAINER_IP="(none)"

# Uptime in human form.
UPTIME=$(uptime 2>/dev/null | sed 's/^ *//' || echo "unknown")

# Container timezone (from env or /etc/localtime symlink).
TZ_VAL="${TZ:-UTC}"

# Active MCP servers declared at the workspace level (note: runtime state
# would require probing claude, which is overkill for this file).
MCPS_LIST="(unknown)"
if command -v jq >/dev/null 2>&1 && [ -r "$WORKSPACE/.mcp.json" ]; then
  MCPS_LIST=$(jq -r '.mcpServers | keys[]' "$WORKSPACE/.mcp.json" 2>/dev/null | sed 's/^/  - /' || echo "(unknown)")
fi

cat > "$OUT" <<EOF
# Container Runtime

Auto-generated by \`docker/scripts/write_container_info.sh\` on container boot.
Do not edit manually — changes are overwritten at the next start.

**Heads up to Claude reading this:** you run inside a Docker container. The
workspace at \`/workspace\` is a bind-mount from the host machine
(\`$HOST_NAME\`) but your processes, filesystem, and network are container-local.
When asked where you run, say "inside a Docker container on $HOST_NAME", not
"on the Mac/Linux".

## Runtime identity

- **Container hostname:** \`$CONTAINER_HOSTNAME\`
- **Host machine:** \`$HOST_NAME\`
- **OS inside container:** $OS_NAME
- **Kernel:** $KERNEL
- **Arch:** $ARCH
- **Timezone:** $TZ_VAL
- **Uptime:** $UPTIME

## User / permissions

- **Process user:** \`agent\` (uid $AGENT_UID, gid $AGENT_GID) — matched to the
  host user so bind-mount files keep the expected owner on the host side.
- **PID 1:** \`tini\`, which supervises \`entrypoint.sh\` → \`start_services.sh\`.

## Paths

| Path | Kind | Purpose |
|---|---|---|
| \`/workspace\` | bind-mount | The agent's working directory on the host; mirror of host-side \`$HOST_NAME:$WORKSPACE\` (roughly; actual host path is set in docker-compose.yml). |
| \`/home/agent\` | named volume | Claude's profile, plugin cache, memory. Opaque to the host — only backed up by docker volume, not by the workspace. |
| \`/opt/agent-admin\` | image layer | Read-only supervisor scripts (entrypoint, start_services, wizard-container). Do not write here. |

## Network

- Outbound bridge at \`$CONTAINER_IP\` (Docker default network). Outbound-only
  — no ports exposed, no Docker socket bound, no inbound listeners.
- Reaches public APIs (Telegram, Anthropic, GitHub, npm) over HTTPS.

## MCP servers configured (workspace-scope)

$MCPS_LIST

EOF

chmod 0644 "$OUT" 2>/dev/null || true
EOF_END=$(wc -l < "$OUT" 2>/dev/null || echo 0)
echo "[container-info] /workspace/CONTAINER.md refreshed (${EOF_END} lines)"
